name: Verilator Build

on:
  workflow_call:

jobs:
  verilator:
    name: Prepare Verilator
    runs-on: ubuntu-latest

    env:
      TOOL_NAME: verilator
      TOOL_VERSION: 476c043
      DEBIAN_FRONTEND: "noninteractive"

    steps:
      - name: Setup Cache Metadata
        id: cache_metadata
        run: |
          cache_date=$(date +"%Y_%m_%d")
          cache_name=cache_${{ env.TOOL_NAME }}_${{ env.TOOL_VERSION }}
          echo "Cache date: "$cache_date
          echo "Cache name: "$cache_name
          echo "cache_date=$cache_date" >> "$GITHUB_ENV"
          echo "cache_name=$cache_name" >> "$GITHUB_ENV"

      - name: Setup cache
        uses: actions/cache@v6.1.0
        id: cache
        timeout-minutes: 60
        with:
          path: |
            /opt/verilator
            /opt/verilator/.cache
            /opt/uvm-verilator
          key: ${{ env.cache_name }}_${{ env.cache_date }}
          restore-keys: ${{ env.cache_name }}_

      - name: Install prerequisites
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install \
            git bear ccache help2man libfl-dev libsystemc-dev mold build-essential \
            autoconf bison

      - name: Build Verilator
        if: ${{ steps.cache.outputs.cache-hit != 'true' }}
        run: |
          git clone https://github.com/antmicro/verilator.git -b riscv-dv-runtime-rebased
          pushd verilator
            fir checkout ${{ env.TOOL_VERSION }}
            autoconf
            ./configure --prefix=/opt/verilator/
            make -j$(nproc)
            make install
          popd
