name: run-tests

on:
  push:
  pull_request:

jobs:
  build-spike:
    uses: ./.github/workflows/build-spike.yml

  build-verilator:
    uses: ./.github/workflows/build-verilator.yml

  generate-config:
    runs-on: ubuntu-latest
    outputs:
      test-types: ${{ steps.test-types.outputs.tests }}
      hash: ${{ steps.hash.outputs.files-hash }}
    steps:
      - uses: actions/checkout@v4
      - id: test-types
        name: Prepare test types
        run: |
          python3 -m pip install pyyaml --break-system-packages
          python3 .github/scripts/parse_testlist.py rv32i > tests.list
          echo "tests=$(cat tests.list)" | tee -a $GITHUB_OUTPUT
      - id: hash
        name: Prepare files' hash
        run: |
          sha256sum **/*.sv **/*.py **/*.yaml > file.hash
          echo "files-hash=$(cat file.hash | cut -d\  -f1 | sha256sum | cut -d\  -f1)" | tee -a $GITHUB_OUTPUT


  generate-code:
    runs-on: ubuntu-latest
    needs: [ generate-config, build-verilator ]
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.generate-config.outputs.test-types) }}
        version: [ verilator ]
        include:
          - test: riscv_arithmetic_basic_test
            version: verilator
    env:
      TOOL_VERSION: 476c043
      CACHE_HASH: ${{ needs.generate-config.outputs.hash }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ccache build-essential mold z3
          echo "NPROC=1" >> $GITHUB_ENV
          echo "UVM_HOME=/opt/uvm-verilator" >> $GITHUB_ENV
          echo "VERILATOR_PATH=/opt/verilator" >> $GITHUB_ENV

      - name: Clone UVM Verilator
        run: |
          git clone https://github.com/antmicro/uvm-verilator.git -b uvm-1.2-dpi
          mv uvm-verilator /opt/uvm-verilator

      - name: Setup Cache Metadata
        id: cache_metadata
        run: |
          date=$(date +"%Y_%m_%d")
          time=$(date +"%Y%m%d_%H%M%S_%N")
          cache_verilator_restore_key=cache_verilator_
          cache_verilator_key=${cache_verilator_restore_key}${{ env.TOOL_VERSION }}_${date}
          cache_code=cache_${{ matrix.test }}_${{ matrix.version }}

          echo "cache_verilator_restore_key=$cache_verilator_restore_key" | tee -a "$GITHUB_ENV"
          echo "cache_verilator_key=$cache_verilator_key" | tee -a "$GITHUB_ENV"
          echo "cache_code=${cache_code}_${{ env.CACHE_HASH }}" | tee -a "$GITHUB_ENV"

      - name: Restore verilator cache
        id: cache-verilator-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /opt/verilator
            /opt/verilator/.cache
            /opt/uvm-verilator
          key: ${{ env.cache_verilator_key }}
          restore-keys: ${{ env.cache_verilator_restore_key }}

      - name: Setup Python 3.9
        run: |
          python3 -m venv ./.venv
          source ./.venv/bin/activate
          python3 -m pip install -r requirements.txt

      - name: Generate Verilator Tests
        if: matrix.version == 'verilator'
        run: |
          set -eo pipefail
          source ./.venv/bin/activate
          python3 run.py --simulator verilator \
            --test ${{ matrix.test }} --start_seed 999 --iterations 1 --batch_size 1 \
            --target rv32i --isa rv32i \
            --mabi ilp32 --steps gen -v -o out 2>&1 | tee test/generate.log
          /opt/verilator/bin/verilator --version

      - name: Cache Code
        uses: actions/cache@v3
        id: cache-code
        timeout-minutes: 60
        with:
          path: out/asm_test
          key: ${{ env.cache_code }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: generate_code_${{ matrix.test }}_${{ matrix.version }}
          path: |
            out/asm_test/*.S


  run-tests:
    runs-on: ubuntu-latest
    needs: [ build-spike, build-verilator, generate-code, generate-config ]
    strategy:
      fail-fast: false
      matrix:
        test: ${{ fromJSON(needs.generate-config.outputs.test-types) }}
        version:
          - verilator
        include:
          - test: riscv_arithmetic_basic_test
            version: verilator
    env:
      TOOL_VERSION: d70ea67d
      CACHE_HASH: ${{ needs.generate-config.outputs.hash }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get -qqy update && sudo apt-get -qqy install device-tree-compiler ccache

      - name: Install cross-compiler
        shell: bash
        run: |
          echo "deb http://archive.ubuntu.com/ubuntu/ noble main universe" | sudo tee -a /etc/apt/sources.list > /dev/null
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install gcc-riscv64-unknown-elf
          riscv64-unknown-elf-gcc --version

      - name: Setup python
        # python dependencies cannot be properly downloaded with new versions of python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install python dependencies
        run: python3 -m pip install -r requirements.txt

      - name: Setup Cache Metadata
        id: cache_metadata
        run: |
          date=$(date +"%Y_%m_%d")
          time=$(date +"%Y%m%d_%H%M%S_%N")
          cache_spike_restore_key=cache_spike_
          cache_spike_key=${cache_spike_restore_key}${{ env.TOOL_VERSION }}_${date}
          cache_code=cache_${{ matrix.test }}_${{ matrix.version }}

          echo "cache_spike_restore_key=$cache_spike_restore_key" | tee -a "$GITHUB_ENV"
          echo "cache_spike_key=$cache_spike_key" | tee -a "$GITHUB_ENV"
          echo "cache_code=${cache_code}_${{ env.CACHE_HASH }}" | tee -a "$GITHUB_ENV"

      - name: Restore Spike cache
        id: cache-spike-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            /opt/spike
            /opt/spike/.cache
          key: ${{ env.cache_spike_key }}
          restore-keys: ${{ env.cache_spike_restore_key }}

      - name: Set variables
        run: |
          echo "RISCV_GCC=riscv64-unknown-elf-gcc" >> $GITHUB_ENV
          echo "RISCV_OBJCOPY=riscv64-unknown-elf-objcopy" >> $GITHUB_ENV
          echo "SPIKE_PATH=/opt/spike/bin" >> $GITHUB_ENV
          echo "PYTHONPATH=pygen" >> $GITHUB_ENV

      - name: Cache Code Restore
        uses: actions/cache/restore@v3
        id: cache-code-restore
        timeout-minutes: 60
        with:
          path: out/asm_test
          key: ${{ env.cache_code }}

      - name: Run Tests
        run: |
          set -eo pipefail
          python3 run.py --simulator pyflow \
            --test ${{ matrix.test }} --iss spike --iss_timeout 60 \
            --start_seed 999 --iterations 1 --batch_size 1 \
            --target rv32i --isa rv32i --mabi ilp32 --noclean \
            --steps gcc_compile,iss_sim -v -o out 2>&1 | tee -a test/generate.log

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: run_tests_log_${{ matrix.test }}_${{ matrix.version }}
          path: |
            test/*.log
            out/**/${{ matrix.test }}*.log
