name: run-tests

on:
  push:
  # TODO :: Disabled now to not run double the jobs needed.
  # pull_request:

jobs:
  build-spike:
    uses: ./.github/workflows/build-spike.yml

  build-verilator:
    uses: ./.github/workflows/build-verilator.yml

  generate-config:
    runs-on: ubuntu-latest
    outputs:
      targets: ${{ steps.test-types.outputs.targets }}
      tests: ${{ steps.test-types.outputs.tests }}
      hash: ${{ steps.hash.outputs.files-hash }}
    steps:
      - uses: actions/checkout@v4
      - id: test-types
        name: Prepare test types
        run: |
          python3 -m pip install pyyaml --break-system-packages
          targets_json='["rv32i", "multi_harts", "rv32imc" ]'
          echo "targets=$targets_json" | tee -a $GITHUB_OUTPUT
          python3 .github/scripts/parse_testlist.py $(echo $targets_json | jq -r '.[]') > tests.list
          echo "tests=$(cat tests.list)" | tee -a $GITHUB_OUTPUT
      - id: hash
        name: Prepare files' hash
        run: |
          shopt -s globstar nullglob
          sha256sum **/*.sv **/*.py **/*.yaml > file.hash
          echo "files-hash=$(cat file.hash | cut -d\  -f1 | sha256sum | cut -d\  -f1)" | tee -a $GITHUB_OUTPUT

  build-generator:
    runs-on: ubuntu-latest
    needs: [ generate-config, build-verilator ]
    strategy:
        fail-fast: false
        matrix:
          target: ${{ fromJSON(needs.generate-config.outputs.targets) }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt-get update -y
          sudo apt-get install -y ccache build-essential mold z3
          echo "NPROC=$(nproc)" >> $GITHUB_ENV
          echo "UVM_HOME=/opt/uvm-verilator" >> $GITHUB_ENV
          echo "VERILATOR_PATH=/opt/verilator" >> $GITHUB_ENV

      - name: Clone UVM Verilator
        run: |
          git clone https://github.com/antmicro/uvm-verilator.git -b uvm-1.2-dpi
          mv uvm-verilator /opt/uvm-verilator

      - name: Setup Cache Metadata
        id: cache_metadata
        run: |
          cache_generator_key=cache_${{ matrix.target }}_${{ needs.build-verilator.outputs.cache_key }}
          files_hash=${{ needs.generate-config.outputs.hash }}
          echo "cache_generator=${cache_generator_key}_${files_hash}" | tee -a "$GITHUB_ENV"

        # python dependencies cannot be properly downloaded with new versions of python
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: python3 -m pip install -r requirements.txt

      - name: Cache Code
        uses: actions/cache@v4
        id: cache-generator
        timeout-minutes: 60
        with:
          path: out/Vuvm
          key: ${{ env.cache_generator }}

      - name: Restore verilator cache
        if: steps.cache-generator.outputs.cache-hit != 'true'
        id: cache-verilator-restore
        uses: actions/cache/restore@v6.1.0
        with:
          path: |
            /opt/verilator
          key: ${{ needs.build-verilator.outputs.cache_key }}
          fail-on-cache-miss: true

      - name: Build Generator
        if: steps.cache-generator.outputs.cache-hit != 'true'
        run: |
          set -eo pipefail
          # source ./.venv/bin/activate
          python3 run.py --simulator verilator --co \
            --target ${{ matrix.target }} \
            -v -o out 2>&1 | tee test/build_generator.log
          /opt/verilator/bin/verilator --version

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: generator_${{ matrix.target }}
          path: |
            out/Vuvm

  run-tests:
    runs-on: ubuntu-latest
    needs: [ build-spike, build-generator, generate-config ]
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.generate-config.outputs.tests) }}

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get -qqy update && sudo apt-get -qqy install device-tree-compiler ccache z3

      - name: Install cross-compiler
        shell: bash
        run: |
          echo "deb http://archive.ubuntu.com/ubuntu/ noble main universe" | sudo tee -a /etc/apt/sources.list > /dev/null
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install gcc-riscv64-unknown-elf
          riscv64-unknown-elf-gcc --version

      - name: Setup python
        # python dependencies cannot be properly downloaded with new versions of python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'
      - run: python3 -m pip install -r requirements.txt

      - name: Restore Spike cache
        id: cache-spike-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            /opt/spike
            /opt/spike/.cache
          key: ${{ needs.build-spike.outputs.cache_key }}
          fail-on-cache-miss: true

      - name: Set variables
        run: |
          echo "RISCV_GCC=riscv64-unknown-elf-gcc" >> $GITHUB_ENV
          echo "RISCV_OBJCOPY=riscv64-unknown-elf-objcopy" >> $GITHUB_ENV
          echo "SPIKE_PATH=/opt/spike/bin" >> $GITHUB_ENV
          echo "PYTHONPATH=pygen" >> $GITHUB_ENV

      - name: Download generator
        uses: actions/download-artifact@v4
        with:
          name: generator_${{ matrix.target }}
          path: out

      - name: Fix environment
        run: | 
          chmod +x out/Vuvm
          echo "UVM_HOME=/opt/uvm-verilator" >> $GITHUB_ENV
          echo "VERILATOR_PATH=/opt/verilator" >> $GITHUB_ENV
          echo "NPROC=$(nproc)" >> $GITHUB_ENV

      - name: Run Tests
        run: |
          set -eo pipefail
          python3 run.py  \
            --target ${{ matrix.target }} --test ${{ matrix.test }} \
            --iss spike --iss_timeout 60 --gen_timeout 720 --start_seed 999 \
            --iterations 1 --batch_size 1 --noclean \
            --simulator verilator \
            --so -o out 2>&1 | tee -a test/generate.log

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: run_tests_log_${{ matrix.target }}_${{ matrix.test }}
          path: |
            test/*.log
            out/**/${{ matrix.test }}*.log
